Search-and-Rescue/Beacon_FE

- components/App/App.js
- components/App/styles.js
- components/Login/Login.js
- components/Login/styles.js
Setups the Login component
Login.js
Snapshot test for the new component
> Login component

- components/CategoryList/CategoryList.js
- components/CategoryList/styles.js
- components/ListItem/ListItem.js
- components/ListItem/styles.js
Setup the reusable components CategoryList and ListItem, which will be used for each category. 
CategoryList.js => ListItem.js
Each file will need multiple snapshot tests depending on which props are being passed through for the specific category.
> List and form components

- components/Home/Home.js
- components/Home/styles.js
- components/Login/Login.js
Initial setup for the Home component.
Home.js
Snapshot test for the Home component.
> Home component

- components/CategoryList/CategoryList.test.js
- components/Home/Home.test.js
- components/ListItem/ListItem.test.js
- components/Login/Login.test.js
- components/Trip/Trip.js
- components/Trip/Trip.test.js
- components/Trip/styles.js
Initial setup for Trip component. Additionally, since Travis CI was set up, I skipped all of the created test files for now. Giving us enough time to understand React Native testing.
Trip.js
Snapshot test will need to be created for this component.
Since we haven't confirmed the dropdown functionality. I put placeholder text in for choosing an emergency contact, vehicle, and gear.
> Trip component

- components/setupTests.js
> Add setupTests.js file for Enzyme adapter

- components/App/App.js
- components/App/App.test.js
- components/App/__snapshots__/App.test.js.snap
- components/CategoryList/CategoryList.js
- components/CategoryList/CategoryList.test.js
- components/CategoryList/__snapshots__/CategoryList.test.js.snap
- components/Home/Home.test.js
- components/Home/__snapshots__/Home.test.js.snap
- components/ListItem/ListItem.test.js
- components/ListItem/__snapshots__/ListItem.test.js.snap
- components/Login/Login.test.js
- components/Login/__snapshots__/Login.test.js.snap
- components/Trip/Trip.js
- components/Trip/Trip.test.js
- components/Trip/__snapshots__/Trip.test.js.snap
- components/setupTests.js
- navigation/navigator.js
- package-lock.json
- package.json
Snapshot tests for all of the existing components:
- App
- Login
- Home
- CategoryList
- ListItem
- WelcomeScreen
Each of the test files, which should be compared to the snapshot file.
The menuButton and DrawerNavigator were mocked out, so the snapshot would stop breaking because it didn't know what these components were. In addition, I had to bring the Adapter for Enzyme into each test file. I initially created a separate file, however I kept getting an error that it was undefined. I researched and it looks like this is a common issue with React Native.
Lastly, the navigation in App file was breaking the snapshot test, thus I moved all of the contents into a separate file.
> Snapshot testing

- components/Contact/Contact.js
- components/Contact/Contact.test.js
- components/Contact/__snapshots__/Contact.test.js.snap
- components/Contact/styles.js
This branch sets up the Contact component, which includes inputs for all emergency contact fields(name, phone, email) along with a button to submit these details later to the database. In addition, it includes some basic styling that the FE team agreed upon for inputs and buttons.
Contact.js
A snapshot was already added in this branch. We will later want to test the click simulation for the button.
> Contact form

- components/App/App.js
- components/Gear/Gear.js
- components/Gear/Gear.test.js
- components/Gear/__snapshots__/Gear.test.js.snap
- components/Gear/styles.js
Add the initial form for a user to add/edit a gear item.
The only file that changed is the Gear component and its test.
Run the test suite to ensure the snapshot passes.
N/A
https://github.com/Search-and-Rescue/SearchAndRescue-FE/issues/54
Should we test the handleSubmit method? At least to ensure it is called onPress.
> Setup gear

- components/Contact/Contact.js
- components/Contact/__snapshots__/Contact.test.js.snap
Corrects the buggy Contact onPress function to call handleSubmit and return to the ContactList.
Contact.js
Check in the simulator.
N/A
https://github.com/Search-and-Rescue/SearchAndRescue-FE/issues/59
N/A
> Handle submit contact

- components/ContactList/ContactList.test.js
- components/ContactList/__snapshots__/ContactList.test.js.snap
- components/GearList/GearList.test.js
- components/GearList/__snapshots__/GearList.test.js.snap
- components/VehicleList/VehicleList.test.js
- components/VehicleList/__snapshots__/VehicleList.test.js.snap
Add missing snapshot tests, so we no longer have an error because there wasn't a test included in some of the test files.
> Snapshot test lists

- components/Profile/Profile.js
- components/Profile/Profile.test.js
- components/Profile/__snapshots__/Profile.test.js.snap
- components/Profile/styles.js
- navigation/StackNavigators/ProfileNavigator.js
- navigation/navigator.js
Adds a base version of the Profile input, which is also accessible from the drawer navigator. I made the ProfileNavigator file, too, but it isn't in play yet. We'll need it to break up the long form into multiple pages. This component will certainly need additional work.
The Profile, test, ProfileNavigator and styles files are all new.
In the emulator and via the test suite. (Snapshot only for now)
I'd like to work together on the rest of this. I figured out how to trigger the different keyboards for the different input types, and how to coerce the datatypes before they're set in state, but I'd like assistance on the date picker for the birthday. We're going to use that elsewhere, so we may just want to use one of the many packages out there. …
> Setup profile

- actions/actions.test.js
- actions/index.js
- components/App/App.js
- components/App/__snapshots__/App.test.js.snap
- package-lock.json
- package.json
- reducers/index.js
- reducers/user.js
- reducers/user.test.js
Initial setup for Redux. At this time I included an action creator for a specific user. However, I wanted to wait on constructing out the rest of the store till we have more specific documentation from the BE team on the API.
App.js - Please note there isn't an index.js file for React Native, thus I had add CreateStore and the Provider into our App.js file.
Tests were created already to test out the action creator and reducer.
I was having trouble setting up Redux Dev tools for React Native. I found a possible solution, however I was unable to run it in dev tools. I have console logged the state and it looks like it stores information. However, I will need to do some more research on the dev tools with React native.
> Setup redux

- actions/index.js
- reducers/contacts.js
- reducers/currentTrip.js
- reducers/gear.js
- reducers/index.js
- reducers/trips.js
- reducers/vehicles.js
Sets up the rest of the Redux store to include Emergency Contacts, Vehicles, Gear, Trips and CurrentTrip.
action index.js
Action creator and reducer tests
> Setup redux store

- components/ContactList/ContactList.js
- components/ContactList/ContactList.test.js
- components/ContactList/__snapshots__/ContactList.test.js.snap
- components/ContactList/styles.js
- components/Login/Login.js
- components/WelcomeScreen/WelcomeScreen.js
- components/WelcomeScreen/WelcomeScreen.test.js
- components/WelcomeScreen/__snapshots__/WelcomeScreen.test.js.snap
- util/apiCalls.js
Fetches all emergency contacts for a specific user and then displays this list on the ContactList page.
apiCalls.js
I updated the snapshot tests for both WelcomeScreen and ContactList. Happy and sad path testing will need to be added.
I'm currently console logging the error for this fetch. Thus we may need to look into options for storing the error message.
> Fetch emergency contacts

- components/Gear/Gear.js
- components/Gear/Gear.test.js
- components/Gear/__snapshots__/Gear.test.js.snap
- components/Gear/styles.js
- components/GearList/GearList.js
- components/GearList/GearList.test.js
- components/GearList/__snapshots__/GearList.test.js.snap
- components/GearList/styles.js
Adds functionality to pass props from an item in the GearList to the Gear component.
Bring up in the simulator, and click on an item in the GearList. The details should appear in the inputs on the Gear page.
N/A
https://github.com/Search-and-Rescue/SearchAndRescue-FE/issues/51
N/A
> Begin gearlist

- components/VehicleList/VehicleList.js
- components/VehicleList/VehicleList.test.js
- components/VehicleList/__snapshots__/VehicleList.test.js.snap
- components/VehicleList/styles.js
- components/WelcomeScreen/WelcomeScreen.js
- util/apiCalls.js
Fetches the list of vehicles for a specific user and displays this list on the vehicleList page.
apiCalls.js
The snapshot test for vehiclesList has been updated. However, we still will want to add tests for the happy and sad paths for fetching the vehicles in apiCalls.js.
> Fetch vehicles

- actions/actions.test.js
- components/Gear/Gear.js
- components/Gear/__snapshots__/Gear.test.js.snap
- components/GearList/GearList.js
- components/GearList/GearList.test.js
- components/GearList/__snapshots__/GearList.test.js.snap
- components/WelcomeScreen/WelcomeScreen.js
- reducers/gear.test.js
- util/apiCalls.js
Sets up fetch call for getting all of the gear for a specific user and then displaying this list on the gearList page.
apiCalls.js
The snapshot test have already been updated. However, we will need to add tests for the happy and sad paths for getGear in apiCalls.
I noticed that I set up item_name incorrectly, so I went through and fixed to itemName to match the database.
> Fetch gear

- components/Contact/Contact.js
- components/Contact/Contact.test.js
- components/Contact/__snapshots__/Contact.test.js.snap
- components/ContactList/ContactList.js
- components/ContactList/ContactList.test.js
- components/ContactList/__snapshots__/ContactList.test.js.snap
- components/Gear/Gear.test.js
- components/GearList/GearList.js
- components/GearList/GearList.test.js
- components/Vehicle/Vehicle.js
- components/Vehicle/Vehicle.test.js
- components/Vehicle/__snapshots__/Vehicle.test.js.snap
- components/VehicleList/VehicleList.js
- components/VehicleList/__snapshots__/VehicleList.test.js.snap
Passes vehicle and contact props to their respective components.
Check the simulator, and make sure vehicle and contact info is showing in the form fields.
N/A
https://github.com/Search-and-Rescue/SearchAndRescue-FE/issues/50
> Vehicle contact pass props

- components/GearList/GearList.js
Moves the editItem method from inside the render.
GearList component file.
It passes the snapshots, so check the simulator.
N/A
https://github.com/Search-and-Rescue/SearchAndRescue-FE/issues/89
N/A
Nope.
> Move method from inside render

- components/WelcomeScreen/WelcomeScreen.js
- util/apiCalls.js
Get all of the profile information for a specific user and all of their trips. Then saves this information to the Redux store.
apiCalls.js
We will need to add happy and sad path tests for all of these methods in apiCalls.
> Fetch trip and profile

- components/Trip/Trip.js
- components/Trip/Trip.test.js
- components/Trip/__snapshots__/Trip.test.js.snap
- components/Trip/styles.js
Adds a new picker/modal for the user to add/remove gear id's from the Trip's gear array.
In Trip.js. I moved the fake data up into state to get a little more organized, and didn't incorporate the apiCalls yet, so there will be clean up to do tomorrow.
This passes the snapshot, but the test will need a little tweak once the apiCalls are included (gear vs. gearArray)
N/A
https://github.com/Search-and-Rescue/SearchAndRescue-FE/issues/91
N/A
> Begin gear checklist

- util/apiCalls.js
Create methods for each fetch method in the apiCalls file. This includes adding a new emergency contact, vehicle, gear Item, and trip.
apiCalls.js
We will want to test happy and sad paths for each method in apiCalls.js file.
> Fetch add items

- components/Contact/Contact.js
- components/Gear/Gear.js
- components/GearList/GearList.js
- components/Vehicle/Vehicle.js
- components/Vehicle/__snapshots__/Vehicle.test.js.snap
This morning I noticed an issue with the Contact, Gear, and Vehicle components creating an error when you try to go to their forms to create a new item. It looks the add button and the bottom navigation were expecting an object to be passed through. However, they were receiving undefined because there wasn't an existing object to revise. Therefore, I added a solution in the constructor which takes an undefined prop and changes it to the expected format. We will probably want to refactor this at a later date, however this for now fixes the problem for both buttons.
Due to the navigator being unique from the "add button", I had to add this conditional to the physical component.
Additionally, while in Vehicle I notice we were using licence_plate, which matches the original schema. However, …
> Fix undefined bug

- components/Contact/Contact.js
- components/Contact/Contact.test.js
- components/Gear/Gear.js
- components/Gear/Gear.test.js
- components/Gear/__snapshots__/Gear.test.js.snap
- components/Vehicle/Vehicle.js
- components/Vehicle/Vehicle.test.js
- components/WelcomeScreen/WelcomeScreen.js
- util/apiCalls.js
Use the apiCall methods in each of the components to add a new vehicle, emergency contact and gear Item. Then update the list of each to include the newly added item.
apiCalls.js - I had to update the structure of the apiCalls methods, because graphQL was expected the query a specific way that JavaScript was not setting up 
Due to adding mapStateToProps and mapDispatchToProps to these components. I had to individually export just the component, so that the snapshot tests would pass.
Fetch add items #98
> Post items

- components/GearList/GearList.js
- util/apiCalls.js
This PR adds functionality to delete an added gear item by id number, then call for all remaining items to update the store and be re-rendered.
GearList.js
It is working in the app and passing our test suite.
N/A
https://github.com/Search-and-Rescue/SearchAndRescue-FE/issues/103
> Gear delete

- components/ContactList/ContactList.js
- components/TripList/TripList.js
- util/apiCalls.js
Adds functionality to delete an emergency contact from the list, then call for remaining contacts, and store them to be re-rendered.
ContactList.js
This works in the App and passes the test suite.
N/A
https://github.com/Search-and-Rescue/SearchAndRescue-FE/issues/103
> Contact delete

- components/GearList/GearList.js
- components/Trip/Trip.js
- components/TripList/TripList.js
- components/TripList/TripList.test.js
- components/TripList/__snapshots__/TripList.test.js.snap
- components/TripList/styles.js
- util/apiCalls.js
This PR adds the "I'm Back" button, aka The Button, which allows a user to deactivate their current trip status to 'active: false', and stop any emergency notifications from being sent. 
TripList.js, Trip.js and the TripList test files were all changed.
Add a new trip, then change the status.
I think it'd be a good user experience to see the Trip name on the button, so will add that to the issue list.
https://github.com/Search-and-Rescue/SearchAndRescue-FE/issues/116
N/A
> Back button

- components/TripList/TripList.js
- components/TripList/__snapshots__/TripList.test.js.snap
- util/apiCalls.js
- Removes a trip from the trip list
- If the trip is an active trip, then it will also be deactivated upon deletion.
apiCalls.js
Snapshot test was already updated due to changes to TripList
Before deleting the trip, a conditional checks if the id matches the id saved in the Redux store. If it does, then the trip is deactivated first before deleting from the page.
> Remove trip

- components/ProfileViewer/ProfileViewer.js
- components/ProfileViewer/ProfileViewer.test.js
- components/ProfileViewer/__snapshots__/ProfileViewer.test.js.snap
- components/ProfileViewer/styles.js
- navigation/StackNavigators/ProfileNavigator.js
- navigation/navigator.js
Adds a new component, the ProfileViewer, to see the user's existing profile information.
ProfileViewer.js and its test file.
Run the the test suite and check the simulator.
This component might be useful place to grab the user photo if we get to that extension.
https://github.com/Search-and-Rescue/SearchAndRescue-FE/issues/126
> Profile viewer

- README.md
Adds the color scheme hex codes to the readme for temporary access.
README.md
Not required.
N/A
Choose color scheme #37
N/A
> Add color scheme to readme for temporary access

- util/apiCalls.js
- util/apiCalls.test.js
Test apiCall methods happy and sad paths for all of the traditionally GET and POST methods. In the case of GraphQL these are built instead with queries and mutations. 
apiCalls.js
Test apiCalls.js #137
> Api calls testing

- README.md
- util/apiCalls.js
Updated the readme to include:
- introduction
- TravisCI badge
- Setup
- Project board link
- List of Beacon team
- Link to BE repo
> Add table of contents with initial details to the readme

- components/Trip/Trip.js
- components/Trip/styles.js
Displays the emergency contacts, gear and vehicle selected by the user in bullet form under each button in the Trip form.
Trip.js
In an attempt to reassure the user which contacts, gear and vehicle they have selected for the trip prior to hitting submit.
> Display dropdown form

- util/apiCalls.test.js
Add happy and sad path tests for the following apiCalls methods:
- Delete Trip
- Delete Emergency Contact
- Delete Vehicle
- Delete Gear Item
- Add Emergency Contact to a specific trip
- Add Vehicle to a specific trip
- Add Gear Item to a specific trip
apiCalls.test.js
After reviewing the coverage, these tests didn't fully cover the lines for the apiCalls file. I will do some research to see if this is a common issue with testing graphQL.
Complete apiCalls tests #146
> Apicalls tests

- navigation/navigator.js
Adds an arrow icon for the Logout TouchableOpacity and adds marginTop to align the Logout at the bottom.
navigation.js
All tests are passing.
No.
https://github.com/Search-and-Rescue/Beacon_FE/issues/166
> Logout icon

- components/Trip/Trip.js
- components/Trip/styles.js
Displays the current dates and times on the Trip form.
Trip.js
Previously the milliseconds were included in the time, because it didn't matter that they were included in the post to the database. However, to clean up the time displayed, I had them removed so it only displays the hour and minutes.
Display selected text from modal in Trip #147 (Displaying the selected gear, vehicle, and contacts was completed in a previous ticket for code fair)
> Display dates and times

- README.md
Updates the image links in the README to include the new gifs (URLS should match once those are merged to master, won't display correctly until then.)
https://github.com/Search-and-Rescue/Beacon_FE/issues/173
> Update readme w/new gifs

- .travis.yml
- components/Trip/Trip.test.js
- components/Trip/__snapshots__/Trip.test.js.snap
Adds a mock of the current date/time saved in Trip's state, so the snapshot test doesn't re-run the new Date method making the test fail.
Trip.test.js
Snapshot is now fixed, so other tests can be completed in this component.
I had to use new Date() for the mocked date, because the method doesn't create a string.
Fix Trip snapshot test #180
> Fix Trip snapshot test

- README.md
Adds the AddTrip gif to the readme file.
Approve the gif in the other PR, then this change to the README should work. The link here follows the syntax of the others.
N/A
> Add the AddTrip gif to the readme

- components/WelcomeScreen/WelcomeScreen.js
- util/apiCalls.js
- util/apiCalls.test.js
Adds a new apiCall for sending the user email/password and getting back a token.
apiCalls and their tests.
This is passing the test suite (with many of the old warnings/errors).
N/A
https://github.com/Search-and-Rescue/Beacon_FE/issues/184
N/A
How much of the returning token actually needs to be stored? TBD.
> Add apiCall and tests for getToken

- components/Contact/Contact.test.js
- components/Gear/Gear.test.js
- components/Profile/Profile.test.js
- components/Trip/Trip.test.js
- components/Vehicle/Vehicle.test.js
Test onChangeText for inputs, mapStateToProps, and mapDispatchToProps for all of the form components (Vehicle, Trip, Profile, Gear, Contact).
I struggled to find a solution for testing when a button is pressed and then a method is called. I'm still doing some research, because it looks to not be a common test in React Native.
Test state and simulations for existing forms #189
> Test forms

- components/SignUp/SignUp.js
- components/SignUp/SignUp.test.js
- components/SignUp/__snapshots__/SignUp.test.js.snap
- components/SignUp/styles.js
Adds a new component, the SignUp form, so a user can register for a new account.
There are three new files and one passing snapshot test.
N/A It won't yet be visible in the app, as there's no navigation to this component.
At the moment, the form is a direct copy of the login form. Updates TBD.
https://github.com/Search-and-Rescue/Beacon_FE/issues/194
N/A
N/A
> Add SignUp component, first snapshot test, styles file

- components/ContactList/ContactList.test.js
- components/GearList/GearList.test.js
- components/ProfileViewer/ProfileViewer.test.js
- components/TripList/TripList.test.js
- components/VehicleList/VehicleList.test.js
- components/WelcomeScreen/WelcomeScreen.test.js
Add tests for mapState and mapDispatch for the following components:
- TripList
- ContactList
- VehicleList
- GearList
- ProfileViewer
- WelcomeScreen
Test mapStateToProps/mapDispatchToProps in list components #192
> Testing components redux
